### ISSUE TITLE
Hi,   here is an error thrown on 4.0.1.   please look into this one.  it's a current node, and reapplied the install script

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#129]
Using the following address for challenges
zcLQ2zRXNtmetjsetjstjstjsrtkjstjkssrksrksrtksrk
2019-02-23 21:25:29 UTC -- Waiting to register
2019-02-23 21:25:29 UTC -- Node already registered. znesnatejsetjkteksrtksrtksrtksrkov1wf. Authenticated.
2019-02-23 21:25:29 UTC -- Saved nodeid=666
2019-02-23 21:29:25 UTC -- Stat check: server:ts1.na blocks:470040  peers:8  bal:0.428  isValidBal:true  queueDepth:0  lastChalBlock:null  lastExecSec:null
2019-02-23 21:29:25 UTC -- Stats received by ts1.na
/home/node/secnodetracker/node_modules/write-file-atomic/index.js:127
    throw err
    ^

Error: EACCES: permission denied, open '/home/node/secnodetracker/config/local/socketoptions.863997055'
    at Object.fs.openSync (fs.js:646:18)
    at writeFileSync (/home/node/secnodetracker/node_modules/write-file-atomic/index.js:114:17)
    at LocalStorage.setItem (/home/node/secnodetracker/node_modules/node-localstorage/LocalStorage.js:188:7)
    at Socket.socket.on (/home/node/secnodetracker/app.js:399:15)
    at Socket.Emitter.emit (/home/node/secnodetracker/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/home/node/secnodetracker/node_modules/socket.io-client/lib/socket.js:278:10)
    at Socket.onpacket (/home/node/secnodetracker/node_modules/socket.io-client/lib/socket.js:236:12)
    at Manager.<anonymous> (/home/node/secnodetracker/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/node/secnodetracker/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/home/node/secnodetracker/node_modules/socket.io-client/lib/manager.js:345:8)

**Comment by 333miiko** [comment]
@phobos777 I'm really busy lately, can you email me @gmail.com I'll see if I can fix this for you

**Comment by phobos777** [comment]
hi!  ironically i was troubleshooting this, and a few other execptions, and i think i figured it out Miiko.   basically with the 4.0.1 tracker it doesn't have permissions to log update to then events.  so the fix it,  after running the install.sh,  i then run this script manually:   

chmod -R 777 /etc/letsencrypt/ && chmod -R 777 /mnt/zen/secnode/ && chmod -R 777 /mnt/zen

i hear your busy, but i did want to update the github,  i guess this would only help?
