### ISSUE TITLE
Challenge from Server is getting failed due to below reason

### ISSUE THREAD

**Issue by Cryptot86** [WhenLamboMoon/docker-zen-node#42]
Hi, 

My node is registered and its up and running but when a challenge is sent it is getting failed with below exception,

Out from Command: docker logs zen-secnodetracker

2017-12-28 02:08:48 GMT -- Start challenge. 399683
Using zcXAbBXGBCoBUL4qL779RWSRi1qbmCPhanqGgniBUY3JNcti9TELzKMzxWBNFmp3mcC8HaLzdDBuK1kq3izCRtKWCCZFFGC for challenge. bal=1.0456
OperationId=opid-a97e77f8-22c6-44d3-b457-745ff3d4551d
2017-12-28 02:08:58 GMT -- Elapsed challenge time=10  status=executing
2017-12-28 02:09:08 GMT -- Elapsed challenge time=20  status=executing
2017-12-28 02:09:18 GMT -- Elapsed challenge time=30  status=executing
2017-12-28 02:09:28 GMT -- Elapsed challenge time=40  status=executing
2017-12-28 02:09:38 GMT -- Elapsed challenge time=50  status=executing
2017-12-28 02:09:48 GMT -- Elapsed challenge time=60  status=executing
2017-12-28 02:09:58 GMT -- Elapsed challenge time=70  status=executing
2017-12-28 02:10:08 GMT -- Elapsed challenge time=80  status=executing
2017-12-28 02:10:18 GMT -- Elapsed challenge time=90  status=executing
2017-12-28 02:10:28 GMT -- Elapsed challenge time=100  status=executing
2017-12-28 02:10:38 GMT -- Elapsed challenge time=110  status=executing
2017-12-28 02:10:48 GMT -- Elapsed challenge time=120  status=executing
2017-12-28 02:10:58 GMT -- Elapsed challenge time=130  status=executing
2017-12-28 02:11:08 GMT -- Elapsed challenge time=140  status=executing
2017-12-28 02:11:18 GMT -- Elapsed challenge time=150  status=executing
2017-12-28 02:11:26 GMT -- Stat check: connected to:ts1.na blocks:229763 peers:9 bal:1.0456 isValidBal:true queueDepth:0 lastChalBlock:null lastExecSec:null
2017-12-28 02:11:28 GMT -- Elapsed challenge time=160  status=executing
2017-12-28 02:11:38 GMT -- Elapsed challenge time=170  status=executing
2017-12-28 02:11:48 GMT -- Elapsed challenge time=180  status=executing
2017-12-28 02:13:17 GMT -- Elapsed challenge time=270  status=executing
2017-12-28 02:13:27 GMT -- Elapsed challenge time=280  status=executing
2017-12-28 02:13:37 GMT -- Elapsed challenge time=290  status=executing
2017-12-28 02:13:47 GMT -- Elapsed challenge time=300  status=executing
2017-12-28 02:13:57 GMT -- Elapsed challenge time=310  status=executing
2017-12-28 02:14:07 GMT -- Elapsed challenge time=320  status=executing
2017-12-28 02:14:17 GMT -- Elapsed challenge time=330  status=executing
2017-12-28 02:14:27 GMT -- Elapsed challenge time=340  status=executing
2017-12-28 02:14:37 GMT -- Elapsed challenge time=350  status=executing
2017-12-28 02:14:47 GMT -- Elapsed challenge time=360  status=executing
2017-12-28 02:14:57 GMT -- Elapsed challenge time=370  status=executing
2017-12-28 02:15:07 GMT -- Elapsed challenge time=380  status=executing
2017-12-28 02:15:17 GMT -- Elapsed challenge time=390  status=executing
2017-12-28 02:15:28 GMT -- Elapsed challenge time=400  status=executing
2017-12-28 02:15:37 GMT -- Elapsed challenge time=410  status=executing
2017-12-28 02:15:48 GMT -- Elapsed challenge time=420  status=executing
2017-12-28 02:15:58 GMT -- Elapsed challenge time=430  status=executing
2017-12-28 02:16:18 GMT -- Elapsed challenge time=450  status=executing
2017-12-28 02:16:28 GMT -- Elapsed challenge time=460  status=executing
2017-12-28 02:16:38 GMT -- Elapsed challenge time=470  status=executing
2017-12-28 02:16:48 GMT -- Elapsed challenge time=480  status=executing
2017-12-28 02:16:58 GMT -- Elapsed challenge time=490  status=executing
2017-12-28 02:17:08 GMT -- Elapsed challenge time=500  status=executing
2017-12-28 02:17:18 GMT -- Elapsed challenge time=510  status=executing
2017-12-28 02:17:26 GMT -- Stat check: connected to:ts1.na blocks:229768 peers:9 bal:1.0456 isValidBal:true queueDepth:0 lastChalBlock:null lastExecSec:null
2017-12-28 02:17:28 GMT -- Elapsed challenge time=520  status=executing
2017-12-28 02:17:38 GMT -- Elapsed challenge time=530  status=executing
2017-12-28 02:17:48 GMT -- Elapsed challenge time=540  status=executing
2017-12-28 02:17:56 GMT -- Challenge submit: success
2017-12-28 02:17:56 GMT -- Challenge result:success seconds:547.899871215
challenge error
{ Error: EACCES: permission denied, open '/home/node/secnodetracker/config/lastExecSec.3101612050'
    at Object.fs.openSync (fs.js:646:18)
    at writeFileSync (/home/node/secnodetracker/node_modules/write-file-atomic/index.js:114:17)
    at LocalStorage.setItem (/home/node/secnodetracker/node_modules/node-localstorage/LocalStorage.js:177:7)
    at self.zenrpc.z_getoperationstatus.then.operation (/home/node/secnodetracker/SecNodeTracker.js:246:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/node/secnodetracker/config/lastExecSec.3101612050' }

**Comment by 333miiko** [comment]
Your challenge should actually be passing if you check the secure node tracker website:

> 2017-12-28 02:17:56 GMT -- Challenge result:success seconds:547.899871215

This is an issue with one of the old versions of the securenodetracker, you can update it by running:

```
systemctl restart zen-secnodetracker
```

**Comment by Cryptot86** [comment]
Thank you , it worked now after the update
