### ISSUE TITLE
Unable to collect stats without a nodeid

### ISSUE THREAD

**Issue by nstreit408** [WhenLamboMoon/docker-zen-node#62]
root@ZENnode01:~# docker logs zen-secnodetracker
Secure node config found OK - linking...
CPU Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz  cores=1  speed=1799
Tracker app version: 0.2.1
MemTotal: 2.00GB  MemFree: 0.07GB  MemAvailable: 1.19GB  SwapTotal: 4.10GB  SwapFree: 3.83GB
2018-02-27 08:06:29 GMT -- Connected to server ts1.NA. Initializing...
Secure Node t_address (not for stake)=znbePdFWF2oYKVG2QEAQKRqDLwbL6wHjDMv
Error: zen getinfo  { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/node/secnodetracker/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  cause: { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/node/secnodetracker/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) code: 'ESOCKETTIMEDOUT', connect: false },
  isOperational: true,
  code: 'ESOCKETTIMEDOUT',
  connect: false }
2018-02-27 08:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:30:29 GMT -- Unable to collect stats without a nodeid.

root@ZENnode01:~# docker logs zen-node
Starting with UID/GID : 9001/9001
Symlinking external zcash-params volume...
Using external data volume
Copying additional trusted SSL certificates
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
149 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Zcash - fetch-params.sh

Zen uses the same zkSNARK parameters generated by ZCash.
This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
Retrieving: https://zensystem.io/downloads/sprout-proving.key
/usr/bin/zen-fetch-params: line 27: sw_vers: command not found
--2018-02-26 22:27:53--  https://zensystem.io/downloads/sprout-proving.key
Resolving zensystem.io (zensystem.io)... 104.27.2.80, 104.27.3.80, 2400:cb00:2048:1::681b:350, ...
Connecting to zensystem.io (zensystem.io)|104.27.2.80|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://f001.backblazeb2.com/file/TrustedSetup/sprout-proving.key [following]
--2018-02-26 22:27:53--  https://f001.backblazeb2.com/file/TrustedSetup/sprout-proving.key
Resolving f001.backblazeb2.com (f001.backblazeb2.com)... 162.244.62.199
Connecting to f001.backblazeb2.com (f001.backblazeb2.com)|162.244.62.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 910173851 (868M) [text/plain]
Saving to: '/home/user/.zcash-params/sprout-proving.key.dl'

     0K ........ ........ ........ ........  3% 39.7M 21s
 32768K ........ ........ ........ ........  7% 71.7M 16s
 65536K ........ ........ ........ ........ 11% 42.7M 16s
 98304K ........ ........ ........ ........ 14% 61.2M 15s
131072K ........ ........ ........ ........ 18% 50.4M 14s
163840K ........ ........ ........ ........ 22% 41.4M 14s
196608K ........ ........ ........ ........ 25% 50.8M 13s
229376K ........ ........ ........ ........ 29% 36.8M 13s
262144K ........ ........ ........ ........ 33% 45.1M 12s
294912K ........ ........ ........ ........ 36% 41.6M 12s
327680K ........ ........ ........ ........ 40% 32.3M 12s
360448K ........ ........ ........ ........ 44% 29.9M 11s
393216K ........ ........ ........ ........ 47% 46.5M 10s
425984K ........ ........ ........ ........ 51% 35.5M 10s
458752K ........ ........ ........ ........ 55% 43.9M 9s
491520K ........ ........ ........ ........ 58% 40.4M 8s
524288K ........ ........ ........ ........ 62% 46.8M 8s
557056K ........ ........ ........ ........ 66% 36.3M 7s
589824K ........ ........ ........ ........ 70% 47.8M 6s
622592K ........ ........ ........ ........ 73%  107M 5s
655360K ........ ........ ........ ........ 77% 88.9M 4s
688128K ........ ........ ........ ........ 81% 74.6M 4s
720896K ........ ........ ........ ........ 84% 94.2M 3s
753664K ........ ........ ........ ........ 88%  103M 2s
786432K ........ ........ ........ ........ 92% 77.7M 1s
819200K ........ ........ ........ ........ 95% 80.7M 1s
851968K ........ ........ ........ ........ 99% 68.4M 0s
884736K ....                               100% 62.5M=17s

2018-02-26 22:28:10 (49.9 MB/s) - '/home/user/.zcash-params/sprout-proving.key.dl' saved [910173851/910173851]

/home/user/.zcash-params/sprout-proving.key.dl: OK
'/home/user/.zcash-params/sprout-proving.key.dl' -> '/home/user/.zcash-params/sprout-proving.key'
Retrieving: https://zensystem.io/downloads/sprout-verifying.key
/usr/bin/zen-fetch-params: line 27: sw_vers: command not found
--2018-02-26 22:28:26--  https://zensystem.io/downloads/sprout-verifying.key
Resolving zensystem.io (zensystem.io)... 104.27.2.80, 104.27.3.80, 2400:cb00:2048:1::681b:350, ...
Connecting to zensystem.io (zensystem.io)|104.27.2.80|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://f001.backblazeb2.com/file/TrustedSetup/sprout-verifying.key [following]
--2018-02-26 22:28:26--  https://f001.backblazeb2.com/file/TrustedSetup/sprout-verifying.key
Resolving f001.backblazeb2.com (f001.backblazeb2.com)... 162.244.62.199
Connecting to f001.backblazeb2.com (f001.backblazeb2.com)|162.244.62.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1449 (1.4K) [text/plain]
Saving to: '/home/user/.zcash-params/sprout-verifying.key.dl'

     0K                                    100%  199M=0s

2018-02-26 22:28:26 (199 MB/s) - '/home/user/.zcash-params/sprout-verifying.key.dl' saved [1449/1449]

/home/user/.zcash-params/sprout-verifying.key.dl: OK
'/home/user/.zcash-params/sprout-verifying.key.dl' -> '/home/user/.zcash-params/sprout-verifying.key'
Starting zend ..
root@ZENnode01:~#

**Comment by m-dennis** [comment]
try restarting node.

docker stop zen-node
systemctl restart zen-node

**Comment by nstreit408** [comment]
Alright rebooted, now getting this return

root@ZENnode01:~# docker logs zen-secnodetracker
Secure node config found OK - linking...
CPU Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz  cores=1  speed=1799
Tracker app version: 0.2.1
MemTotal: 2.00GB  MemFree: 0.07GB  MemAvailable: 1.19GB  SwapTotal: 4.10GB  SwapFree: 3.83GB
2018-02-27 08:06:29 GMT -- Connected to server ts1.NA. Initializing...
Secure Node t_address (not for stake)=znbePdFWF2oYKVG2QEAQKRqDLwbL6wHjDMv
Error: zen getinfo  { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/node/secnodetracker/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  cause: { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/node/secnodetracker/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) code: 'ESOCKETTIMEDOUT', connect: false },
  isOperational: true,
  code: 'ESOCKETTIMEDOUT',
  connect: false }
2018-02-27 08:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 08:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 09:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 10:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 11:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 12:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 13:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 14:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 15:54:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:00:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:06:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:12:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:18:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:24:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:30:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:36:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:42:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:48:29 GMT -- Unable to collect stats without a nodeid.
2018-02-27 16:54:29 GMT -- Unable to collect stats without a nodeid.

**Comment by nstreit408** [comment]
root@ZENnode01:~# docker logs zen-node
Starting with UID/GID : 9001/9001
Symlinking external zcash-params volume...
Using external data volume
Copying additional trusted SSL certificates
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
149 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Zcash - fetch-params.sh

Zen uses the same zkSNARK parameters generated by ZCash.
This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
Starting zend ..

**Comment by 333miiko** [comment]
Can you try re-run the installer?
