### ISSUE TITLE
challenge -exceeded reply time or timed out

### ISSUE THREAD

**Issue by m-dennis** [WhenLamboMoon/docker-zen-node#63]
anyone know the issue here?

root@vps519077:~# docker logs zen-secnodetracker
Secure node config found OK - linking...
CPU Intel Core Processor (Haswell, no TSX)  cores=1  speed=2394
Tracker app version: 0.2.1
MemTotal: 3.86GB  MemFree: 0.11GB  MemAvailable: 3.20GB  SwapTotal: 1.02GB  SwapFree: 0.99GB
2018-02-27 13:16:04 GMT -- Connected to server ts1.eu. Initializing...
2018-02-27 13:16:04 GMT -- Zend: Loading block index...
Waiting on zend
2018-02-27 13:16:14 GMT -- Zend: Verifying blocks...
Waiting on zend
2018-02-27 13:16:24 GMT -- Zend: Verifying blocks...
Waiting on zend
Secure Node t_address (not for stake)=znTSGfhTqpJEFK47txxswCN4CTgfFiqoKgq
Balance for challenge transactions is 1
Using the following address for challenges
zceC5DfAUMDP65mqa357rbdz6c3rx7z9fLd5rNmuuYgqjy5UQgTEyo3qRcPjruh9iy2tK1tEqEesuhPjfJAe61kRf2E8uQt
2018-02-27 13:16:36 GMT -- Registration successful. Welcome!
2018-02-27 13:18:31 GMT -- Start challenge. 2517957
Using zceC5DfAUMDP65mqa357rbdz6c3rx7z9fLd5rNmuuYgqjy5UQgTEyo3qRcPjruh9iy2tK1tEqEesuhPjfJAe61kRf2E8uQt for challenge. bal=1
OperationId=opid-2dbc2cc3-c9e4-4ebc-ab26-3f6185064557
2018-02-27 13:18:41 GMT -- Elapsed challenge time=10  status=executing
2018-02-27 13:18:51 GMT -- Elapsed challenge time=20  status=executing
2018-02-27 13:19:01 GMT -- Elapsed challenge time=30  status=executing
2018-02-27 13:19:11 GMT -- Elapsed challenge time=40  status=executing
2018-02-27 13:19:21 GMT -- Elapsed challenge time=50  status=executing
2018-02-27 13:19:31 GMT -- Elapsed challenge time=60  status=executing
2018-02-27 13:19:41 GMT -- Elapsed challenge time=70  status=executing
2018-02-27 13:19:51 GMT -- Elapsed challenge time=80  status=executing
2018-02-27 13:20:01 GMT -- Elapsed challenge time=90  status=executing
2018-02-27 13:20:11 GMT -- Elapsed challenge time=100  status=executing
2018-02-27 13:20:21 GMT -- Elapsed challenge time=110  status=executing
2018-02-27 13:20:32 GMT -- Elapsed challenge time=120  status=executing
2018-02-27 13:20:42 GMT -- Elapsed challenge time=130  status=executing
2018-02-27 13:20:52 GMT -- Elapsed challenge time=140  status=executing
2018-02-27 13:21:02 GMT -- Elapsed challenge time=150  status=executing
2018-02-27 13:21:12 GMT -- Elapsed challenge time=160  status=executing
2018-02-27 13:21:22 GMT -- Elapsed challenge time=170  status=success
2018-02-27 13:21:22 GMT -- Challenge submit: success
2018-02-27 13:21:22 GMT -- Challenge result:success seconds:169.889501703
2018-02-27 13:21:24 GMT -- Clearing timer
2018-02-27 13:22:04 GMT -- Stat check: connected to:ts1.eu blocks:264590 peers:8 bal:0.9998 isValidBal:false queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 13:22:04 GMT -- Stats received by ts1.eu
2018-02-27 13:28:04 GMT -- Stat check: connected to:ts1.eu blocks:264603 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 13:28:04 GMT -- Stats received by ts1.eu
2018-02-27 13:34:04 GMT -- Stat check: connected to:ts1.eu blocks:264606 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 13:34:04 GMT -- Stats received by ts1.eu
2018-02-27 13:40:04 GMT -- Stat check: connected to:ts1.eu blocks:264609 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 13:40:04 GMT -- Stats received by ts1.eu
2018-02-27 13:46:04 GMT -- Stat check: connected to:ts1.eu blocks:264610 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 13:46:04 GMT -- Stats received by ts1.eu
2018-02-27 13:51:34 GMT -- Cert check: valid=true.  Hostname zen7.colohash.com matches CN zen7.colohash.com
2018-02-27 13:52:04 GMT -- Stat check: connected to:ts1.eu blocks:264611 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 13:52:04 GMT -- Stats received by ts1.eu
2018-02-27 13:58:04 GMT -- Stat check: connected to:ts1.eu blocks:264612 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 13:58:04 GMT -- Stats received by ts1.eu
2018-02-27 14:04:04 GMT -- Stat check: connected to:ts1.eu blocks:264613 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:04:04 GMT -- Stats received by ts1.eu
2018-02-27 14:10:04 GMT -- Stat check: connected to:ts1.eu blocks:264614 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:10:04 GMT -- Stats received by ts1.eu
2018-02-27 14:16:04 GMT -- Stat check: connected to:ts1.eu blocks:264614 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:16:04 GMT -- Stats received by ts1.eu
2018-02-27 14:22:04 GMT -- Stat check: connected to:ts1.eu blocks:264615 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:22:04 GMT -- Stats received by ts1.eu
2018-02-27 14:28:04 GMT -- Stat check: connected to:ts1.eu blocks:264616 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:28:04 GMT -- Stats received by ts1.eu
2018-02-27 14:33:16 GMT -- Cert check: valid=true.  Hostname zen7.colohash.com matches CN zen7.colohash.com
2018-02-27 14:34:04 GMT -- Stat check: connected to:ts1.eu blocks:264619 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:34:04 GMT -- Stats received by ts1.eu
2018-02-27 14:40:04 GMT -- Stat check: connected to:ts1.eu blocks:264620 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:40:04 GMT -- Stats received by ts1.eu
2018-02-27 14:46:04 GMT -- Stat check: connected to:ts1.eu blocks:264621 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:46:04 GMT -- Stats received by ts1.eu
2018-02-27 14:52:04 GMT -- Stat check: connected to:ts1.eu blocks:264622 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:52:04 GMT -- Stats received by ts1.eu
2018-02-27 14:56:41 GMT -- Start challenge. 2520289
2018-02-27 14:56:41 GMT -- Challenge Error: unable to get blockhash for challenge id 2520289 block 4916
2018-02-27 14:57:42 GMT -- Zen connected.
2018-02-27 14:57:42 GMT -- Stat check: connected to:ts1.eu blocks:264622 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:57:42 GMT -- Stats received by ts1.eu
2018-02-27 14:58:04 GMT -- Stat check: connected to:ts1.eu blocks:264623 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 14:58:04 GMT -- Stats received by ts1.eu
2018-02-27 15:04:04 GMT -- Stat check: connected to:ts1.eu blocks:264627 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:04:04 GMT -- Stats received by ts1.eu
2018-02-27 15:10:04 GMT -- Stat check: connected to:ts1.eu blocks:264635 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:10:04 GMT -- Stats received by ts1.eu
2018-02-27 15:14:59 GMT -- Cert check: valid=true.  Hostname zen7.colohash.com matches CN zen7.colohash.com
2018-02-27 15:16:04 GMT -- Stat check: connected to:ts1.eu blocks:264645 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:16:04 GMT -- Stats received by ts1.eu
2018-02-27 15:22:04 GMT -- Stat check: connected to:ts1.eu blocks:264654 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:22:04 GMT -- Stats received by ts1.eu
2018-02-27 15:28:04 GMT -- Stat check: connected to:ts1.eu blocks:264657 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:28:04 GMT -- Stats received by ts1.eu
2018-02-27 15:34:04 GMT -- Stat check: connected to:ts1.eu blocks:264659 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:34:04 GMT -- Stats received by ts1.eu
2018-02-27 15:40:04 GMT -- Stat check: connected to:ts1.eu blocks:264659 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:40:04 GMT -- Stats received by ts1.eu
2018-02-27 15:46:04 GMT -- Stat check: connected to:ts1.eu blocks:264660 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:46:04 GMT -- Stats received by ts1.eu
2018-02-27 15:52:04 GMT -- Stat check: connected to:ts1.eu blocks:264661 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:52:04 GMT -- Stats received by ts1.eu
2018-02-27 15:56:38 GMT -- Cert check: valid=true.  Hostname zen7.colohash.com matches CN zen7.colohash.com
2018-02-27 15:58:04 GMT -- Stat check: connected to:ts1.eu blocks:264663 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 15:58:04 GMT -- Stats received by ts1.eu
2018-02-27 16:04:04 GMT -- Stat check: connected to:ts1.eu blocks:264666 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:04:04 GMT -- Stats received by ts1.eu
2018-02-27 16:10:04 GMT -- Stat check: connected to:ts1.eu blocks:264666 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:10:04 GMT -- Stats received by ts1.eu
2018-02-27 16:16:04 GMT -- Stat check: connected to:ts1.eu blocks:264666 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:16:04 GMT -- Stats received by ts1.eu
2018-02-27 16:22:04 GMT -- Stat check: connected to:ts1.eu blocks:264669 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:22:04 GMT -- Stats received by ts1.eu
2018-02-27 16:28:04 GMT -- Stat check: connected to:ts1.eu blocks:264670 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:28:04 GMT -- Stats received by ts1.eu
2018-02-27 16:34:04 GMT -- Stat check: connected to:ts1.eu blocks:264671 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:34:04 GMT -- Stats received by ts1.eu
2018-02-27 16:38:21 GMT -- Cert check: valid=true.  Hostname zen7.colohash.com matches CN zen7.colohash.com
2018-02-27 16:40:04 GMT -- Stat check: connected to:ts1.eu blocks:264674 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:40:04 GMT -- Stats received by ts1.eu
2018-02-27 16:43:44 GMT -- Start challenge. 2522909
Using zceC5DfAUMDP65mqa357rbdz6c3rx7z9fLd5rNmuuYgqjy5UQgTEyo3qRcPjruh9iy2tK1tEqEesuhPjfJAe61kRf2E8uQt for challenge. bal=0.9998
OperationId=opid-38ab746e-1c4d-459b-a259-75882b0245b4
2018-02-27 16:43:54 GMT -- Elapsed challenge time=10  status=executing
2018-02-27 16:44:04 GMT -- Elapsed challenge time=20  status=executing
2018-02-27 16:44:14 GMT -- Elapsed challenge time=30  status=executing
2018-02-27 16:44:24 GMT -- Elapsed challenge time=40  status=executing
2018-02-27 16:44:34 GMT -- Elapsed challenge time=50  status=executing
2018-02-27 16:44:44 GMT -- Elapsed challenge time=60  status=executing
2018-02-27 16:44:54 GMT -- Elapsed challenge time=70  status=executing
2018-02-27 16:45:04 GMT -- Elapsed challenge time=80  status=executing
2018-02-27 16:45:14 GMT -- Elapsed challenge time=90  status=executing
2018-02-27 16:45:24 GMT -- Elapsed challenge time=100  status=executing
2018-02-27 16:45:34 GMT -- Elapsed challenge time=110  status=executing
2018-02-27 16:45:44 GMT -- Elapsed challenge time=120  status=executing
2018-02-27 16:45:54 GMT -- Elapsed challenge time=130  status=executing
2018-02-27 16:46:04 GMT -- Stat check: connected to:ts1.eu blocks:264676 peers:8 bal:0.9998 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:46:04 GMT -- Stats received by ts1.eu
2018-02-27 16:46:04 GMT -- Elapsed challenge time=140  status=executing
2018-02-27 16:46:14 GMT -- Elapsed challenge time=150  status=executing
2018-02-27 16:46:24 GMT -- Elapsed challenge time=160  status=executing
2018-02-27 16:46:30 GMT -- Challenge submit: success
2018-02-27 16:46:30 GMT -- Challenge result:success seconds:165.88199773
2018-02-27 16:46:30 GMT -- Challenge error: could not get operation status.
{ Error: EACCES: permission denied, open '/mnt/zen/secnode/lastExecSec.2393835286'
    at Object.fs.openSync (fs.js:646:18)
    at writeFileSync (/home/node/secnodetracker/node_modules/write-file-atomic/index.js:114:17)
    at LocalStorage.setItem (/home/node/secnodetracker/node_modules/node-localstorage/LocalStorage.js:177:7)
    at self.zenrpc.z_getoperationstatus.then.operation (/home/node/secnodetracker/SecNodeTracker.js:259:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/mnt/zen/secnode/lastExecSec.2393835286' }
2018-02-27 16:52:04 GMT -- Stat check: connected to:ts1.eu blocks:264680 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:52:04 GMT -- Stats received by ts1.eu
2018-02-27 16:58:04 GMT -- Stat check: connected to:ts1.eu blocks:264684 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 16:58:04 GMT -- Stats received by ts1.eu
2018-02-27 17:04:04 GMT -- Stat check: connected to:ts1.eu blocks:264693 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 17:04:04 GMT -- Stats received by ts1.eu
2018-02-27 17:10:04 GMT -- Stat check: connected to:ts1.eu blocks:264693 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 17:10:04 GMT -- Stats received by ts1.eu
2018-02-27 17:16:04 GMT -- Stat check: connected to:ts1.eu blocks:264693 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 17:16:04 GMT -- Stats received by ts1.eu
2018-02-27 17:20:00 GMT -- Cert check: valid=true.  Hostname zen7.colohash.com matches CN zen7.colohash.com
2018-02-27 17:22:04 GMT -- Stat check: connected to:ts1.eu blocks:264694 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 17:22:04 GMT -- Stats received by ts1.eu
2018-02-27 17:28:04 GMT -- Stat check: connected to:ts1.eu blocks:264696 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 17:28:04 GMT -- Stats received by ts1.eu
2018-02-27 17:34:04 GMT -- Stat check: connected to:ts1.eu blocks:264697 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 17:34:04 GMT -- Stats received by ts1.eu
2018-02-27 17:40:04 GMT -- Stat check: connected to:ts1.eu blocks:264697 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 17:40:04 GMT -- Stats received by ts1.eu
2018-02-27 17:46:04 GMT -- Stat check: connected to:ts1.eu blocks:264698 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 17:46:04 GMT -- Stats received by ts1.eu
2018-02-27 17:52:04 GMT -- Stat check: connected to:ts1.eu blocks:264699 peers:8 bal:0.9996 isValidBal:true queueDepth:0 lastChalBlock:264588 lastExecSec:169.89
2018-02-27 17:52:04 GMT -- Stats received by ts1.eu

**Comment by m-dennis** [comment]
Ok I got this cleared. For anyone experiencing similar issues, I ended up just rebuilding the node (actually did it twice) and then it worked.

**Comment by 333miiko** [comment]
This would generally indicate your VPS specs are not powerful enough.
Ensure you meet the minimum memory limits for the zen node
