### ISSUE TITLE
IMPORTANT UPGRADE NOTICE

### ISSUE THREAD

**Issue by 333miiko** [WhenLamboMoon/docker-zen-node#82]
**IMPORTANT NOTES FOR UPGRADING**

The securenode tracker uses a new configuration meaning if you upgrade through the normal restart process it will break.

There are two options for fixing your config:

- Re-run the installer again, this will re-generate the new config which is compatible with the latest version (remember to grab the latest version first)

- Update the config manually, remember to replace all the variables starting with $

cat << EOF > /mnt/zen/secnode/config.json
{
 "active": "secure",
 "secure": {
  "nodetype": "secure",
  "nodeid": null,
  "servers": [
   "ts2.eu",
   "ts1.eu",
   "ts3.eu",
   "ts4.eu",
   "ts4.na",
   "ts3.na",
   "ts2.na",
   "ts1.na"
  ],
  "stakeaddr": "$stakeaddr",
  "email": "$email",
  "fqdn": "$fqdn",
  "ipv": "4",
  "region": "$region",
  "home": "ts1.$region",
  "category": "none"
 }
}
EOF

**Comment by phobos777** [comment]
see my discord PM's to you.  most notable last remark

**Comment by Spiral11** [comment]
I used the second method and the tracker log was outputting this error:

2018-07-17 16:42:53 UTC -- connect ENETUNREACH 127.0.0.0:80 - Local (0.0.0.0:0)

Fix was to stop zend, edit zen.conf and change 
rpcallowip=127.0.0.0/24 
to
rpcallowip=127.0.0.1

Not really sure how this error is related to the tracker but it happened right after I restarted it so if anyone else encounters it, there's the solution.

**Comment by slayorktc** [comment]
I used your new install script and I saw it created config.json but in the logs I am getting this error:

Jul 17 18:48:34 mn1 systemd[1]: Started Zen Secnodetracker Container.
Jul 17 18:48:35 mn1 docker[9370]: Secure node config found OK - linking...
Jul 17 18:48:36 mn1 docker[9370]: Retrieving zen rpc config....
Jul 17 18:48:36 mn1 docker[9370]: /home/node/secnodetracker/app.js:23
Jul 17 18:48:36 mn1 docker[9370]: if (config.ipv === '6') {
Jul 17 18:48:36 mn1 docker[9370]: ^
Jul 17 18:48:36 mn1 docker[9370]: TypeError: Cannot read property 'ipv' of undefined
Jul 17 18:48:36 mn1 docker[9370]: at Object. (/home/node/secnodetracker/app.js:23:12)
Jul 17 18:48:36 mn1 docker[9370]: at Module._compile (module.js:652:30)
Jul 17 18:48:36 mn1 docker[9370]: at Object.Module._extensions..js (module.js:663:10)
Jul 17 18:48:36 mn1 docker[9370]: at Module.load (module.js:565:32)
Jul 17 18:48:36 mn1 docker[9370]: at tryModuleLoad (module.js:505:12)
Jul 17 18:48:36 mn1 docker[9370]: at Function.Module._load (module.js:497:3)
Jul 17 18:48:36 mn1 docker[9370]: at Function.Module.runMain (module.js:693:10)
Jul 17 18:48:36 mn1 docker[9370]: at startup (bootstrap_node.js:191:16)
Jul 17 18:48:36 mn1 docker[9370]: at bootstrap_node.js:612:3




Is there a syntax error with the three '==='. Should it only be two ==?

**Comment by phobos777** [comment]
i commented on Discord i should of said.  :)

**Comment by slayorktc** [comment]
I noticed that a directory called "local" was created in /mnt/zen/secnode. Is that correct?

**Comment by 333miiko** [comment]
@slayorktc you should have a file called config.json in that folder. Did that not get created?

**Comment by 333miiko** [comment]
@slayorktc could you post the content of config.json (redact your email, hostname and stakeaddr)

**Comment by slayorktc** [comment]
{
 "active": "",
 "secure": {
  "nodetype": "",
  "nodeid": null,
  "servers": [
   "ts2.eu",
   "ts1.eu",
   "ts3.eu",
   "ts4.eu",
   "ts4.na",
   "ts3.na",
   "ts2.na",
   "ts1.na"
  ],
  "stakeaddr": "x",
  "email": "x",
  "fqdn": "snode1.convergegroup.tech",
  "ipv": "4",
  "region": "na",
  "home": "ts1.na",
  "category": "none"
 }
}

**Comment by 333miiko** [comment]
Did you use the new parameter at the end of the installer to define it as a secure node?

**Comment by 333miiko** [comment]
The error seems to be because it can't read the config of what ip format you are using. Did you try restart the service in case you didn't get the most latest image?

**Comment by 333miiko** [comment]
Are you running the command inside the container or outside? It should be done outside as /mnt/zen/secnode/ will get mounted into the container

**Comment by slayorktc** [comment]
Outside the container. Ran it sitting inside /mnt/zen/secnode

**Comment by 333miiko** [comment]
```
systemctl stop zen-secnodetracker
docker run --rm -v /mnt/zen:/mnt/zen --name secnode -it --entrypoint=/bin/bash whenlambomoon/secnodetracker 
cd /home/node/nodetracker
ls config
node setup
node app
```

**Comment by slayorktc** [comment]
cd /home/node/nodetracker -- Didn't exist but did you mean 'secnodetracker'?

**Comment by slayorktc** [comment]
***Configuration for super node saved. Setup complete!***
root@46306da1ec86:/home/node/secnodetracker# node app
Retrieving zen rpc config....
STARTING NODETRACKER
CPU Intel(R) Xeon(R) CPU D-1521 @ 2.40GHz count=4 speed=2399
Node.js version: v8.11.3
Tracker app version: 0.3.0
Node type: super
MemTotal: 7.98GB  MemFree: 4.48GB  MemAvailable: 6.70GB  SwapTotal: 8.19GB  SwapFree: 8.19GB  
2018-07-18 01:55:00 UTC -- Connected to server xns1.eu. Initializing...
2018-07-18 01:55:00 UTC -- ERROR zend get t-address
2018-07-18 01:55:00 UTC -- connect ENETUNREACH 127.0.0.0:80 - Local (0.0.0.0:0)
2018-07-18 01:55:10 UTC -- ERROR zend get t-address
2018-07-18 01:55:10 UTC -- connect ENETUNREACH 127.0.0.0:80 - Local (0.0.0.0:0)

**Comment by 333miiko** [comment]
Yep sorry /home/node/secnodetracker there would be a config folder in there now

Now the last issue is you need to exit out and modify /mnt/zen/config/zen.conf

and change the line that starts with rpcallowip to be `rpcallowip=127.0.0.1`

**Comment by slayorktc** [comment]
Okay. Getting closer. I know have this error:

Jul 18 04:16:02 mn1 docker[19097]: External IP address (externalip=) not found in zen.conf. At least one (IPv4 or IP
Jul 18 04:16:02 mn1 docker[19097]: If multiple, add the externalip= for each address on a separate line.
Jul 18 04:16:03 mn1 systemd[1]: zen-secnodetracker.service: Service hold-off time over, scheduling restart

**Comment by 333miiko** [comment]
Glad you got it working! I don't think externalip is required, that may have just been due to the earlier rpc issues.

Let me know if you have any other issues.

**Comment by phobos777** [comment]
@333miiko   on reboot of a secure or supernode; the securenode tracker is now requiring one 'externalip' for secure and two external ip (ipv4 and ipv6 for supers).    here is an output of the secnode tracker.  (i also go a new email this morning from the zen dev team)

root@localhost:~# docker logs -f zen-secnodetracker
Secure node config found OK - linking...
Retrieving zen rpc config....
External IP address (externalip=) not found in zen.conf. At least one (IPv4 or IPv6) required for secure nodes. Both IPv4 and IPv6 required for super nodes.
If multiple, add the externalip= for each address on a separate line.

**Comment by phobos777** [comment]
and add port while your there please:   LOL:  

root@localhost:~# docker logs -f zen-secnodetracker
Secure node config found OK - linking...
Retrieving zen rpc config....
Port not found in zen.conf. Add 'port=9033' for mainnet or 'port=19033' for testnet
root@localhost:~#

**Comment by slayorktc** [comment]
Agreed. externalip=
port= 
change 127.0.0.1

How do I deal with having ipv6 and ipv4? Do I need to have two certs? Not exactly sure how to get that working correctly..

**Comment by 333miiko** [comment]
Can you open and close any code or terminal outputs with ``` that way it's formatted. 

Hmm, this externalip and port bit is new. 

@slayorktc you won't need two certs, certs are attached to the hostname (fqdn) not IP address. So in your DNS platform attach the ipv4 and ipv6 addresses to the same hostname.

**Comment by slayorktc** [comment]
Anybody else having issues with cert check false?
Jul 19 20:26:58 zen docker[1616]: 2018-07-19 19:26:58 UTC -- Cert check: valid=false.  unable to verify the first certificate

**Comment by slayorktc** [comment]
Hmmm all my nodes are giving me this now after running the latest install script.

Jul 19 21:02:57 zen docker[1714]: 2018-07-19 20:02:57 UTC -- Authenticated. Nice to see you connected again.
Jul 19 21:02:57 zen docker[1714]: 2018-07-19 20:02:57 UTC -- Updated server list
Jul 19 21:02:57 zen docker[1714]: 2018-07-19 20:02:57 UTC -- Stats: send initial stats.
Jul 19 21:02:57 zen docker[1714]: 2018-07-19 20:02:57 UTC -- Saved servers=ts1.na,ts2.na,ts3.na,ts4.na,ts1.eu,ts2.eu,ts3.eu,ts4.eu
Jul 19 21:02:57 zen docker[1714]: 2018-07-19 20:02:57 UTC -- Stats received by ts1.na
Jul 19 21:02:57 zen docker[1714]: 2018-07-19 20:02:57 UTC -- Cert check: valid=false.  unable to verify the first certificate
Jul 19 21:02:58 zen docker[1714]: 2018-07-19 20:02:58 UTC -- Down time logged. See server.
Jul 19 21:02:58 zen docker[1714]: 2018-07-19 20:02:58 UTC -- Down time logged. See server.
Jul 19 21:02:58 zen docker[1714]: 2018-07-19 20:02:58 UTC -- Down time logged. See server.

**Comment by phobos777** [comment]
yes, happening to me as well.  also see my other issue, with is another varient.  he'll have to work on that part next for us.  :)

**Comment by slayorktc** [comment]
Ah sorry! I forgot I meant to post this.. Here is a fix I used to update all my nodes.. This is assuming everything has been up and running for awhile.. Log in and run:

curl -O https://raw.githubusercontent.com/slayorktc/zen-node-upgrade-fix/master/fix.sh
sudo chmod +x fix.sh
sudo ./fix.sh

Look at the script. It basically pulls in all the info from the secnode directory, then updates the zen.conf to be correct and then drops in a config.json. Don't use this for a super node. Only secure node.

Glad someone else has the ssl issue as well.. Hope there is a fix and a credit for this false issue. (I hope its on the zen teams side not our side.. :) )

**Comment by phobos777** [comment]
HUGE THANK YOU!!!

**Comment by phobos777** [comment]
@slayorktc    i'll have to play around with it more.  it feels like it's not pulling all the variables.  here is the output.  feels like its not running MNT docker image

root@Z20bWLM:~# docker logs -f zen-secnodetracker
Secure node config found OK - linking...
Retrieving zen rpc config....
STARTING NODETRACKER
CPU Virtual CPU 82d9ed4018dd count=1 speed=2600
Node.js version: v8.11.3
Tracker app version: 0.3.1
Node type: secure
MemTotal: 2.00GB  MemFree: 0.10GB  MemAvailable: 1.72GB  SwapTotal: 4.10GB  SwapFree: 4.06GB
2018-07-19 21:39:09 UTC -- No connection to server ts1.. Retry.
2018-07-19 21:39:39 UTC -- No connection to server ts1.. Retry.
2018-07-19 21:40:09 UTC -- No connection to server ts1.. Retry.
2018-07-19 21:40:10 UTC -- Trying server: ts2.eu
2018-07-19 21:40:11 UTC -- Connected to server ts2.eu. Initializing...
2018-07-19 21:40:11 UTC -- ERROR zend get t-address
2018-07-19 21:40:11 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:40:21 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:40:21 UTC -- ERROR zend get t-address
2018-07-19 21:40:31 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:40:31 UTC -- ERROR zend get t-address
2018-07-19 21:40:41 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:40:41 UTC -- ERROR zend get t-address
2018-07-19 21:40:51 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:40:51 UTC -- ERROR zend get t-address
2018-07-19 21:41:01 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:41:01 UTC -- ERROR zend get t-address
2018-07-19 21:41:11 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:41:11 UTC -- ERROR zend get t-address
2018-07-19 21:41:21 UTC -- ERROR zend get t-address
2018-07-19 21:41:21 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:41:31 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:41:31 UTC -- ERROR zend get t-address
2018-07-19 21:41:41 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:41:41 UTC -- ERROR zend get t-address
2018-07-19 21:41:51 UTC -- connect ECONNREFUSED 127.0.0.1:18231
2018-07-19 21:41:51 UTC -- ERROR zend get t-address

**Comment by slayorktc** [comment]
What does your zen.conf look like? The script should spit out all the variables it will use at the beginning. I always only getting that error when 127.0.0.1 was not set.

**Comment by slayorktc** [comment]
I think I found the potential issue... I guess a new requirement is to add the ca.cer to the key store. Normally you run update-ca-certificates but i guess that is being added to the machine and not inside the docker containers.. How do I make it so it has the .crt inside the docker container?

**Comment by slayorktc** [comment]
How do I change access to the zend/entrypoint.sh script?

I need to cp /mnt/zen/certs/$FQDN/ca.cer to /usr/local/share/ca-certificates
then run update-ca-certificates

Hopefully that resolves all the fqdn cert failures

**Comment by 333miiko** [comment]
One moment I'll push a fix

**Comment by slayorktc** [comment]
sweet. I really hope this solves the problem.. been messing with this all day!

**Comment by 333miiko** [comment]
Pushed the fix to include the ca back into the container

**Comment by 333miiko** [comment]
https://hub.docker.com/r/whenlambomoon/zend/builds/b6dvjeucxrzx2gfcxn2na59/

**Comment by slayorktc** [comment]
Testing it.

**Comment by 333miiko** [comment]
It's not yet finished building, wait for it here https://hub.docker.com/r/whenlambomoon/zend/builds/

**Comment by slayorktc** [comment]
Phew.. Was just going to say it didn't work still.. Still a chance.. If this doesn't fix it, I have no clue...

**Comment by slayorktc** [comment]
Build "ERROR"

**Comment by 333miiko** [comment]
@slayorktc build finished

**Comment by slayorktc** [comment]
Weird. I now have this error:
2018-07-20 03:10:59 UTC -- connect ECONNREFUSED 127.0.0.1:18231

I wasn't having that one for awhile.. strange.

**Comment by 333miiko** [comment]
Is your zend container running?

**Comment by slayorktc** [comment]
Oh. This is why:

 /usr/local/bin/entrypoint.sh: line 82: syntax error: unexpected end of file

**Comment by slayorktc** [comment]
Are you missing an fi on line 59?

**Comment by slayorktc** [comment]
Actually 62-69 not sure which if goes with which fi.. Somewhere in there I think there is a mismatch

**Comment by 333miiko** [comment]
https://hub.docker.com/r/whenlambomoon/zend/builds/

**Comment by slayorktc** [comment]
Well, I don't know.. Still getting the cert false error.. Did you get it working 33miiko on your vps?

I really have no clue what is causing the issue now..
Jul 20 04:33:25 zen docker[24101]: 2018-07-20 03:33:25 UTC -- Cert check: valid=false.  unable to verify the first certificate

**Comment by 333miiko** [comment]
Can you paste me the log output of your zen-node and zen-secnodetracker

**Comment by slayorktc** [comment]
- Logs begin at Fri 2018-07-20 04:39:48 BST, end at Fri 2018-07-20 04:41:28 BST. --
Jul 20 04:42:13 zen systemd[1]: Starting Zen Daemon Container...
Jul 20 04:42:13 zen docker[1517]: Error response from daemon: No such container: zen-node
Jul 20 04:42:13 zen docker[1538]: Error response from daemon: No such container: zen-node
Jul 20 04:42:15 zen docker[1561]: latest: Pulling from whenlambomoon/zend
Jul 20 04:42:15 zen docker[1561]: Digest: sha256:5e57f35d4d8e9482633f74bf60396eb6841023179ffd5658c732a57804ee3939
Jul 20 04:42:15 zen docker[1561]: Status: Image is up to date for whenlambomoon/zend:latest
Jul 20 04:42:15 zen systemd[1]: Started Zen Daemon Container.
Jul 20 04:42:17 zen docker[1624]: Starting with UID/GID : 9001/9001
Jul 20 04:42:17 zen docker[1624]: Symlinking external zcash-params volume...
Jul 20 04:42:17 zen docker[1624]: Using external data volume
Jul 20 04:42:17 zen docker[1624]: Copying additional trusted SSL certificates
Jul 20 04:42:17 zen docker[1624]: Clearing symlinks in /etc/ssl/certs...
Jul 20 04:42:19 zen docker[1624]: done.
Jul 20 04:42:19 zen docker[1624]: Updating certificates in /etc/ssl/certs...
Jul 20 04:42:24 zen docker[1624]: 149 added, 0 removed; done.
Jul 20 04:42:24 zen docker[1624]: Running hooks in /etc/ca-certificates/update.d...
Jul 20 04:42:24 zen docker[1624]: done.
Jul 20 04:42:24 zen docker[1624]: Zcash - fetch-params.sh
Jul 20 04:42:24 zen docker[1624]: Zen uses the same zkSNARK parameters generated by ZCash.
Jul 20 04:42:24 zen docker[1624]: This script will fetch the Zcash zkSNARK parameters and verify their
Jul 20 04:42:24 zen docker[1624]: integrity with sha256sum.
Jul 20 04:42:24 zen docker[1624]: If they already exist locally, it will exit now and do nothing else.
Jul 20 04:42:24 zen docker[1624]: Starting zend ..

 04:42:30 zen docker[1618]: STARTING NODETRACKER
Jul 20 04:42:30 zen docker[1618]: CPU Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz count=2 speed=2933
Jul 20 04:42:30 zen docker[1618]: Node.js version: v8.11.3
Jul 20 04:42:30 zen docker[1618]: Tracker app version: 0.3.1
Jul 20 04:42:30 zen docker[1618]: Node type: secure
Jul 20 04:42:30 zen docker[1618]: Node Id: 26125
Jul 20 04:42:30 zen docker[1618]: MemTotal: 3.95GB  MemFree: 1.21GB  MemAvailable: 3.28GB  SwapTotal: 3.07GB  SwapFree: 3.07GB
Jul 20 04:42:30 zen docker[1618]: 2018-07-20 03:42:30 UTC -- Connected to server ts1.eu. Initializing...
Jul 20 04:42:30 zen docker[1618]: 2018-07-20 03:42:30 UTC -- Zend: Waiting - Loading block index...
Jul 20 04:40:26 zen docker[1618]: 2018-07-20 03:40:26 UTC -- Zend: Waiting - Loading block index...
Jul 20 04:40:36 zen docker[1618]: 2018-07-20 03:40:36 UTC -- Zend: Waiting - Loading block index...
Jul 20 04:40:46 zen docker[1618]: 2018-07-20 03:40:46 UTC -- Zend: Waiting - Verifying blocks...
Jul 20 04:40:56 zen docker[1618]: 2018-07-20 03:40:56 UTC -- Zend: Waiting - Verifying blocks...
Jul 20 04:41:06 zen docker[1618]: 2018-07-20 03:41:06 UTC -- Zend: Waiting - Verifying blocks...
Jul 20 04:41:16 zen docker[1618]: 2018-07-20 03:41:16 UTC -- Zend: Waiting - Loading wallet...
Jul 20 04:41:26 zen docker[1618]: Node t_address (not for stake)=zndLB1RWYn6XpiYUF82BXjqsEF6mvo2Qhxd
Jul 20 04:41:26 zen docker[1618]: Checking private z-addresses...
Jul 20 04:41:26 zen docker[1618]: Balance for challenge transactions is 0.9796
Jul 20 04:41:26 zen docker[1618]: Using the following address for challenges
Jul 20 04:41:26 zen docker[1618]: zcMpuJHxhtc1eP5orrvUFLT5DYdX3nWZkFgNX68PbfCrN1fKw3k4Bqyi5XXn9mYxer864ymG4Q2fibv8v5AxQ54jKxGcdY
Jul 20 04:41:27 zen docker[1618]: 2018-07-20 03:41:27 UTC -- Authenticated. Nice to see you connected again.
Jul 20 04:41:27 zen docker[1618]: 2018-07-20 03:41:27 UTC -- Updated server list
Jul 20 04:41:27 zen docker[1618]: 2018-07-20 03:41:27 UTC -- Stats: send initial stats.
Jul 20 04:41:27 zen docker[1618]: 2018-07-20 03:41:27 UTC -- Saved servers=ts1.eu,ts2.eu,ts3.eu,ts4.eu,ts1.na,ts2.na,ts3.na,ts4.
Jul 20 04:41:27 zen docker[1618]: 2018-07-20 03:41:27 UTC -- Stats received by ts1.eu
Jul 20 04:41:27 zen docker[1618]: 2018-07-20 03:41:27 UTC -- Cert check: valid=false.  unable to verify the first certificate
Jul 20 04:41:28 zen docker[1618]: 2018-07-20 03:41:28 UTC -- Down time logged. See server.
Jul 20 04:41:28 zen docker[1618]: 2018-07-20 03:41:28 UTC -- Down time logged. See server.
Jul 20 04:41:28 zen docker[1618]: 2018-07-20 03:41:28 UTC -- Down time logged. See server.

**Comment by 333miiko** [comment]
Is there any chance your cert may have already expired? Could you try restart the acme.sh container then restart the node containers to see if it fixes the problem?

Not seeing this happen

**Comment by slayorktc** [comment]
I have regenerated the cert multiple times. Your nodes aren't having any cert issues?

**Comment by slayorktc** [comment]
Well, I just deleted everything and ran the install script again from scratch and the cert worked.. No clue what got messed up with the old setup.. Thanks for the help.

**Comment by 333miiko** [comment]
I didn't have any cert issues.

@phobos777 is your certs ok?

**Comment by slayorktc** [comment]
Phew. After some crazy commands and a couple scripts I got everything back up and running. Just a FYI.. I didn't know this but I had like 10gigs worth of old images just laying around.. 

You can remove untagged images by running:

# hint osx users: your version of xargs won’t have the -r switch
# so just skip it (you may encounter an error if there are no
# images to clean up)

docker images --no-trunc | grep '<none>' | awk '{ print $3 }' \
    | xargs -r docker rmi

**Comment by 333miiko** [comment]
Yes each time you update the old image won't be removed. As mentioned earlier I'll look into implementing certbot and also include the auto update and image clearing when I'm back.

**Comment by darkoopa** [comment]
Hello,
I had to reboot a VPS and the node didn't connect anymore, I looked at it :  "no such container:  zen secnodetracker".

So I supposed it comes from this problem. I tried to manually update the config, it created the config.json but the node is still down.
when i try `docker exec zen-node gosu user zen-cli getinfo`, I get "Secure node config found OK - linking..." but that's all, I don't have the follow up :/

I have this: 
{
 "active": "secure",
 "secure": {
  "nodetype": "secure",
  "nodeid": null,
  "servers": [
   "ts2.eu",
   "ts1.eu",
   "ts3.eu",
   "ts4.eu",
   "ts4.na",
   "ts3.na",
   "ts2.na",
   "ts1.na"
  ],
  "stakeaddr": "znczr8VZormcEUYKrS9YuLiBVSSG76VaVzT",
  "email": "dark.oopa@gmail.com",
  "fqdn": "znode2.darkoopa.pw",
  "ipv": "4",
  "region": "na",
  "home": "ts3.na",
  "category": "none"
 }
}

I tried to change the home to ts3.na and the region to na as that apparently where it supposed to be https://securenodes4.eu.zensystem.io/nodes/9007/detail but normally the OVH server is in france...

I tried with region eu and hone ts1.eu but it was the same.

thx

**Comment by 333miiko** [comment]
Did you restart the node after you updated the config?

**Comment by darkoopa** [comment]
yeah :D I'm really bad at linux but i know to always try to reboot ^^

**Comment by darkoopa** [comment]
it will create a new shielded address right?

**Comment by 333miiko** [comment]
No, if one exists it will not. It's safe to re-run the installer multiple times

**Comment by darkoopa** [comment]
ah ok, I was affraid of that, that's why I didn't do it. i'll try, thx

**Comment by darkoopa** [comment]
It worked, thx.
I supposed I can take back 0.95 ZEN from the shielded address as apparently now yoçu only need 0.05?

**Comment by lutzk87** [comment]
Hey, can someone provide a little tutorial for upgrading the nodetracker to the latest version 0.3.1? i used this tutorial for the secure node because iam a real noob with linux. thanks!

**Comment by 333miiko** [comment]
As mentioned above, re-running the installer above is the best way to upgrade:

```
curl -O https://raw.githubusercontent.com/WhenLamboMoon/docker-zen-node/master/install.sh
chmod +x install.sh
./install.sh <stakeaddr> <email> <fqdn> <region> <nodetype>
```
